name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Project and Resolve Dependencies
        run: ./gradlew build

      - name: "Generate gradle lockfile"
        run: |
          echo "allprojects { dependencyLocking { lockAllConfigurations() } }" >> ~/.gradle/init.gradle
          ./gradlew dependencies --write-locks

      - name: "Run vulnerability analysis"
        uses: phorus-group/vulnerability-analysis-action@main
